server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/red_green_blue?useUnicode=true&characterEncoding=utf-8&useSSL=true&verifyServerCertificate=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 980720
  session:
      store-type: none

security:
  basic:
    enabled: true