server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&verifyServerCertificate=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 980720
  session:
      store-type: none

security:
  basic:
    enabled: true

xhj:
   security:
#      browser:
#        loginPage: /demo-signIn.html
#       设置返回的类型
#        loginType: JSON
      code:
        image:
          length: 6
          width: 60
          url: /user/*